config/routes.rb
Rails.application.routes.draw do
  root "lists#index"
  resources :articles, except: :index

  get "up" => "rails/health#show", as: :rails_health_check

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_one_attached :poster

  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list), notice: "Bookmark was successfully added!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.find(params[:id])
    @bookmark.destroy
    redirect_to @list, notice: "Bookmark deleted successfully."
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list), notice: "List created successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a movie to the list"<%= @list.name %>"</h1>

<%= form_with model: @bookmark, url: list_bookmarks_path(@list), local: true do |form| %>
  <div class="form-group">
    <%= form.label :movie_id, "Choose a filme" %>
    <%= form.collection_select :movie_id, Movie.all, :id, :title, { prompt: "Select a film" }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :comment, "Comment" %>
    <%= form.text_area :comment, class: "form-control" %>
  </div>

  <%= form.submit "Add", class: "btn btn-success" %>
<% end %>

<%= link_to "Back", list_path(@list), class: "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-lewagon">
      <div class="container">
        <a class="navbar-brand" href="/">RailsWatchList</a>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner">
  <h1>Watch List</h1>
</div>

<div class="lists-container">
  <% @lists.each do |list| %>
    <div class="list-item">
      <%= link_to list.name, list_path(list), class: "list-link" %>
    </div>
  <% end %>
</div>

<div class="d-flex justify-content-center">
<%= link_to "Create a new list", new_list_path, class: "btn btn-danger text-white rounded" %>
</div>

app/views/lists/new.html.erb
<h1>Create a new list</h1>

<%= form_with model: @list, local: true do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <%= form.submit "Create a list", class: "btn btn-success" %>
<% end %>

<%= link_to "Back", lists_path, class: "btn btn-secondary" %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<div class="row my-2">
  <% @list.movies.each_with_index do |movie, index| %>
    <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>

    <div class="col-md-4 mb-3 p-3">
      <div class="movie-card p-3">
        <h3><%= movie.title %></h3>

        <% movie.poster.attached %>
          <%= cl_image_tag movie.poster.key, width: 300, height: 200, crop: :fill, alt: "Movie Poster", class: "img-fluid" %>

        <%= form_with model: bookmark, method: :delete, url: list_bookmark_path(@list, bookmark), local: true do |form| %>
          <%= form.submit "Delete", class: "btn btn-danger text-white rounded" %>
        <% end %>
      </div>
    </div>

    <% if (index + 1) % 3 == 0 %>
      </div><div class="row my-2">
    <% end %>
  <% end %>
</div>

<div class="d-flex justify-content-center">
  <%= link_to "Back", lists_path, class: "btn btn-secondary rounded" %>
</div>